(function() {var implementors = {};
implementors['jit'] = ["<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitAnd.html' title='core::ops::BitAnd'>BitAnd</a>&lt;<a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>, <a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>&gt; for <a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitAnd.html' title='core::ops::BitAnd'>BitAnd</a>&lt;<a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>, <a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>&gt; for <a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitAnd.html' title='core::ops::BitAnd'>BitAnd</a>&lt;<a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>, <a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>&gt; for <a class='struct' href='jit/struct.CallFlags.html' title='jit::CallFlags'>CallFlags</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitAnd.html' title='core::ops::BitAnd'>BitAnd</a>&lt;<a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>, <a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>&gt; for <a class='struct' href='jit/struct.TypeKind.html' title='jit::TypeKind'>TypeKind</a>","<a class='stability Experimental' title='Experimental'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitAnd.html' title='core::ops::BitAnd'>BitAnd</a>&lt;<a class='struct' href='jit/struct.Value.html' title='jit::Value'>Value</a>&lt;'a&gt;, <a class='struct' href='jit/struct.Value.html' title='jit::Value'>Value</a>&lt;'a&gt;&gt; for <a class='struct' href='jit/struct.Value.html' title='jit::Value'>Value</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
